name: Update demo files

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  generate-gif:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ss_25_tps_100
        uses: PabloLec/website-to-gif@main
        with:
          url: "https://docs.github.com/en/get-started"
          save_path: '/docs/images'
          file_name: ss_25_tps_100
          scroll_step: 25
          time_per_frame: 100
      - name: ss_50_tps_50
        uses: PabloLec/website-to-gif@main
        with:
          url: "https://docs.github.com/en/get-started"
          save_path: '/docs/images'
          file_name: ss_50_tps_50
          scroll_step: 50
          time_per_frame: 50
      - name: ss_50_tps_100
        uses: PabloLec/website-to-gif@main
        with:
          url: "https://docs.github.com/en/get-started"
          save_path: '/docs/images'
          file_name: ss_50_tps_100
          scroll_step: 50
          time_per_frame: 100
      - name: ss_50_tps_200
        uses: PabloLec/website-to-gif@main
        with:
          url: "https://docs.github.com/en/get-started"
          save_path: '/docs/images'
          file_name: ss_50_tps_200
          scroll_step: 50
          time_per_frame: 200
      - name: Commit file to GH repo
        run: |
          git config --global user.name "PabloLec/website-to-gif"
          git config --global user.email "action@github.com"
          git add .
          git commit -m 'Update file'
          git push
